### ISSUE TITLE
Default buttons on thank you pages for cash payments

### ISSUE THREAD

**Issue by cezarlz** [ebanx/woocommerce-gateway-ebanx#287]
#### Expected behavior and actual behavior.
In some thank you pages, we are using buttons to do some actions, like copy the boleto's code, print the boleto, save a pdf of boleto, etc. But, in some themes these button are rendering wrong. I think the solution is force our own style.

May the code can be:
```css
.our_button_here {
background-color: black;
color: white;
padding: 8px 15px;
border: 0;
text-decoration: none;
font-size: 16px;
}
```

This code can be a starter pointer. 

#### Steps to reproduce the problem.
Do a boleto payment.

#### Specifications like the version of the project, operating system, or hardware.
Plugin: 1.1.0
OS: macOS
